// DO NOT EDIT: This file is autogenerated by https://github.com/0x51-dev/upeg.
package abnf

import (
	"github.com/0x51-dev/upeg/parser/op"
)

var (
	ALPHA  = op.Or{op.RuneRange{Min: 0x41, Max: 0x5A}, op.RuneRange{Min: 0x61, Max: 0x7A}}
	BIT    = op.Or{'0', '1'}
	CHAR   = op.RuneRange{Min: 0x01, Max: 0x7F}
	CR     = rune(0x0D)
	CRLF   = op.And{op.Optional{Value: CR}, LF}
	CTL    = op.Or{op.RuneRange{Min: 0x00, Max: 0x1F}, rune(0x7F)}
	DIGIT  = op.RuneRange{Min: 0x30, Max: 0x39}
	DQUOTE = rune(0x22)
	HEXDIG = op.Or{DIGIT, op.RuneRange{Min: 0x41, Max: 0x46}, op.RuneRange{Min: 0x61, Max: 0x66}}
	HTAB   = rune(0x09)
	LF     = rune(0x0A)
	LWSP   = op.ZeroOrMore{Value: op.Or{WSP, op.And{CRLF, WSP}}}
	OCTET  = op.RuneRange{Min: 0x00, Max: 0xFF}
	SP     = rune(0x20)
	VCHAR  = op.RuneRange{Min: 0x21, Max: 0x7E}
	WSP    = op.Or{SP, HTAB}
)
